### ISSUE TITLE
How do I use it 🤔😅

### ISSUE THREAD

**Issue by Mqxx** [SandResidence/PingWheelBukkit#2]
Hey it's nice that you have written a plugin implementation for the mod, however, I find in the repository only the source code 😅

Is there an already built version as JAR release? Would be cool, because then you could download the JAR directly and would not have to build the JAR from the source code yourself. I don't have much experience with java or how to build the JAR.

**Comment by SandResidence** [comment]
Hi!
You can build the source code by executing `maven clean install` in your terminal.

**Comment by Mqxx** [comment]
@SandResidence My friend build the JAR but now I am getting the following error:
```
[21:36:42] [Server thread/WARN]: [PingWheel] Plugin PingWheel v1.0-SNAPSHOT generated an exception whilst handling plugin message
java.lang.NoClassDefFoundError: com/sk89q/worldguard/protection/flags/registry/FlagConflictException
	at me.axerr.pingwheel.ping.PingListener.isInsidePingableWorldGuardRegion(PingListener.java:61) ~[PingWheel-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at me.axerr.pingwheel.ping.PingListener.isPingAllowed(PingListener.java:34) ~[PingWheel-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at me.axerr.pingwheel.ping.PingListener.onPluginMessageReceived(PingListener.java:23) ~[PingWheel-1.0-SNAPSHOT-jar-with-dependencies.jar:?]
	at org.bukkit.plugin.messaging.StandardMessenger.dispatchIncomingMessage(StandardMessenger.java:455) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.handleCustomPayload(ServerGamePacketListenerImpl.java:3667) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundCustomPayloadPacket.handle(ServerboundCustomPayloadPacket.java:37) ~[?:?]
	at net.minecraft.network.protocol.game.ServerboundCustomPayloadPacket.handle(ServerboundCustomPayloadPacket.java:15) ~[?:?]
	at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:51) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.20.1.jar:git-Purpur-2014]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1366) ~[purpur-1.20.1.jar:git-Purpur-2014]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[purpur-1.20.1.jar:git-Purpur-2014]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1343) ~[purpur-1.20.1.jar:git-Purpur-2014]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1336) ~[purpur-1.20.1.jar:git-Purpur-2014]
	at net.minecraft.util.thread.BlockableEventLoop.runAllTasks(BlockableEventLoop.java:114) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1452) ~[purpur-1.20.1.jar:git-Purpur-2014]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1192) ~[purpur-1.20.1.jar:git-Purpur-2014]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.1.jar:git-Purpur-2014]
	at java.lang.Thread.run(Thread.java:1589) ~[?:?]
Caused by: java.lang.ClassNotFoundException: com.sk89q.worldguard.protection.flags.registry.FlagConflictException
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:185) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:152) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
	... 21 more
```
